global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: "producer"
    static_configs:
      - targets:
          - producer:3000

  - job_name: "consumer"
    static_configs:
      - targets:
          - consumer:9091
rule_files:
  - "alerts/*.yml"
